---
title: "penalty_model"
author: "Jarrod Pelkofer"
date: "12/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries
```{r}
library(tidyverse, warn.conflicts = FALSE)
library(tidymodels)
library(DataExplorer)

options(dplyr.summarise.inform = FALSE)


theme_set(theme_minimal())

source("scripts/defensive_holding_analysis_functions.R")
```


# Data Organization/Prep
```{r}
# filters out for offensive players that drew the defensive holding call
closest_offensive_players_tbl <- read_rds("closest_offensive_players_tbl.rds")

dh_plays <- closest_offensive_players_tbl %>%
  unnest(nearest_off_players) %>%
  select(game_id, play_id, nfl_id_off) %>%
  left_join(select(dh_separation_plays_cleaned, everything()), by = c("game_id", "play_id", "nfl_id_off")) %>%
  mutate(dh = 1)


# random sample of plays where defensive holding was not called
non_dh_plays <- non_dh_plays_df %>% 
  mutate(dh = 0)

# bind data sets
plays_df <- bind_rows(dh_plays, non_dh_plays_df)

# filter out football position and QB's
plays_filtered_df <- plays_df %>% 
  filter(!off_pos %in% c(NA, "QB"))
```


#* Filter for events between ball_snap and pass_thrown/sack/etc
```{r}
plays_frame_filtered_df <- 
  plays_filtered_df %>% 
  group_by(game_id, play_id, frame_id, nfl_id_off) %>% 
  filter(distance_from_opponent == min(distance_from_opponent)) %>% 
  ungroup() %>% 
  nest(-c(game_id, play_id, nfl_id_off)) %>% 
  mutate(filtered_data = map(data, purrr::possibly(filter_frame_func, otherwise = NA)))

plays_frame_filtered_unnested <- plays_frame_filtered_df %>% 
  # five plays blew up during filter frame function, those will be removed
  drop_na() %>% 
  select(-data) %>% 
  unnest(filtered_data)

plays_frame_fixed <- plays_frame_filtered_unnested %>% 
  mutate(dh = ifelse(is.na(dh), 0, 1))

# write_rds(plays_frame_fixed, "plays_frame_fixed.rds")

plays_frame_fixed <- read_rds("plays_frame_fixed.rds")
```


# Create Features
```{r}

data <- plays_frame_fixed %>% 
  filter(game_id %in% c("2018111808") & play_id %in% c(3780) & nfl_id_off %in% c(497322))


# function to create features
create_features_function <- function(data) {
  
  # summarise for modeling features: play length, largest decrease in speed, acceleration, distance, closest distance to opp  
  features_data_1 <-
    data %>%
    arrange(frame_id) %>%
    mutate(
      seconds_from_snap = row_number() / 10, # length of play from snap to throw/sack
      change_in_speed_1 = s_off - lag(s_off, default = 0), # change in speed from last frame
      change_in_speed_2 = s_off - lag(s_off, n = 2, default = 0),
      change_in_speed_3 = s_off - lag(s_off, n = 3, default = 0),
      change_in_speed_4 = s_off - lag(s_off, n = 4, default = 0),
      change_in_speed_5 = s_off - lag(s_off, n = 5, default = 0),
      change_in_speed_6 = s_off - lag(s_off, n = 6, default = 0),
      change_in_speed_7 = s_off - lag(s_off, n = 7, default = 0),
      change_in_speed_8 = s_off - lag(s_off, n = 8, default = 0),
      change_in_speed_9 = s_off - lag(s_off, n = 9, default = 0),
      change_in_speed_10 = s_off - lag(s_off, n = 10, default = 0),
      change_in_acceleration = a_off - lag(a_off, default = 0), # change in acceleration from last frame
      change_in_distance = dis_off - lag(dis_off, default = 0),# change in distance from last frame
      distance_times_speed = s_off*distance_from_opponent # distance from opp multiplied by speed of offensive player
    ) %>%
    mutate(
      change_in_distance_times_speed_1 = distance_times_speed - lag(distance_times_speed, default = 0),
      change_in_distance_times_speed_2 = distance_times_speed - lag(distance_times_speed, n = 2, default = 0),
      change_in_distance_times_speed_3 = distance_times_speed - lag(distance_times_speed, n = 3, default = 0),
      change_in_distance_times_speed_4 = distance_times_speed - lag(distance_times_speed, n = 4, default = 0),
      change_in_distance_times_speed_5 = distance_times_speed - lag(distance_times_speed, n = 5, default = 0),
      change_in_distance_times_speed_6 = distance_times_speed - lag(distance_times_speed, n = 6, default = 0),
      change_in_distance_times_speed_7 = distance_times_speed - lag(distance_times_speed, n = 7, default = 0),
      change_in_distance_times_speed_8 = distance_times_speed - lag(distance_times_speed, n = 8, default = 0),
      change_in_distance_times_speed_9 = distance_times_speed - lag(distance_times_speed, n = 9, default = 0),
      change_in_distance_times_speed_10 = distance_times_speed - lag(distance_times_speed, n = 10, default = 0)
    ) %>% 
    summarise(
      play_length = max(seconds_from_snap),
      across(starts_with("change_in"),
             .fns = min,
             .names = "min_{col}"),
      min_distance_from_opp = min(distance_from_opponent),
      avg_distance_from_opp = mean(distance_from_opponent, na.rm = TRUE),
      dh = max(dh)
    )
  
  # filter for single observation to get down, yards to go, defender in box, player locations at snap of ball
  features_data_2 <- data %>% 
    filter(event %in% "ball_snap") %>% 
    select(down, yards_to_go, defenders_in_the_box, personnel_o, personnel_d,
           x_off_at_snap = x_off, y_off_at_snap = y_off, x_def_at_snap = x_def, y_def_at_snap = y_def)
  
  # speed difference between receiver and defender
  features_data_3 <- data %>% 
    mutate(speed_difference = s_off - s_def) %>% 
    select(distance_from_opponent, speed_difference) %>% 
    summarise(max_speed_differece = max(speed_difference),
              min_speed_difference = min(speed_difference))
  
  # determine if player was defended by man coverage
  features_data_4 <- 
    data %>%
    select(nfl_id_def, event, frame_id) %>%
    group_by(nfl_id_def) %>%
    summarise(total = n()) %>%
    mutate(percentage_as_closest_defender = total / sum(total)) %>%
    mutate(man_coverage = ifelse(percentage_as_closest_defender >= .95, 1, 0)) %>% 
    ungroup() %>% 
    filter(percentage_as_closest_defender == max(percentage_as_closest_defender)) %>% 
    select(nfl_id_def, percentage_as_closest_defender, man_coverage)
  
  
  features_data <- bind_cols(features_data_1, features_data_2, features_data_3, features_data_4)
  
  return(features_data)
  
}

# nest plays
plays_nested <- plays_frame_fixed %>%
  nest(-c(game_id, play_id, nfl_id_off))

# run features function
plays_added_features_nested <- plays_nested %>% 
  mutate(features = map(data, purrr::possibly(create_features_function, otherwise = NA)))

feature_data <- plays_added_features_nested %>%
  select(-data) %>%
  unnest(features) %>%
  drop_na() %>%
  mutate(dh = dh %>% as.factor()) %>%
  # add offensive player weight and height
  left_join(
    select(
      player_data,
      nfl_id,
      off_height = height,
      off_weight = weight
    ),
    by = c("nfl_id_off" = "nfl_id")
  ) %>%
  # add defensive player weight and height
  left_join(
    select(
      player_data,
      nfl_id,
      def_height = height,
      def_weight = weight
    ),
    by = c("nfl_id_def" = "nfl_id")
  ) %>%
  # calculate weight and height adv
  mutate(off_height_adv = off_height - def_height,
         off_weight_adv = off_weight - def_weight,
         down = down %>% as.factor(),
         man_coverage = man_coverage %>% as.factor())


```


# Data Split
```{r}

set.seed(33)
data_split <- initial_split(feature_data, strata = dh)
train_data <- training(data_split)
test_data <- testing(data_split)

```

# Exploration
```{r}

train_data %>% 
  plot_histogram()

train_data %>% 
  select(contains("distance_from_opp"), contains("adv"), def_height, def_weight, off_height, off_weight, percentage_as_closest_defender, 
         play_length, x_off_at_snap, y_off_at_snap, dh) %>% 
  pivot_longer(-dh, names_to = "stat") %>% 
  ggplot(aes(stat, value)) +
  geom_boxplot(aes(color = dh)) +
  facet_wrap(~ stat, scales = "free")

train_data %>% 
  select(min_speed_difference, max_speed_differece, dh) %>% 
  pivot_longer(-dh, names_to = "stat") %>% 
  ggplot(aes(stat, value)) +
  geom_boxplot(aes(color = dh)) +
  facet_wrap(~ stat, scales = "free")

train_data %>% 
  select(contains("min_change_in_distance_times_speed"), dh) %>% 
  pivot_longer(-dh, names_to = "stat") %>% 
  ggplot(aes(stat, value)) +
  geom_boxplot(aes(color = dh)) +
  labs(title = "") +
  facet_wrap(~ stat, scales = "free")


# down looks significant, particularly fourth down
train_data %>%
  select(down, dh) %>% 
  group_by(down) %>% 
  count(dh) %>% 
  ungroup() %>% 
  pivot_wider(names_from = dh, values_from = n) %>% 
  rename(no_dh = `0`, dh = `1`) %>% 
  mutate(percent_dh = dh/(dh+no_dh)) %>% 
  ggplot(aes(down, percent_dh)) +
  geom_col() + 
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Down",
       y = "",
       title = "Defensive Holding Calls Increase by Down")

# man vs. zone looks significant
train_data %>% 
  select(dh, man_coverage) %>% 
  group_by(man_coverage) %>% 
  count(dh) %>%
  ungroup() %>% 
  pivot_wider(names_from = dh, values_from = n) %>% 
  rename(no_dh = `0`, dh = `1`) %>% 
  mutate(percent_dh = dh/(dh+no_dh)) %>% 
  ggplot(aes(man_coverage, percent_dh)) +
  geom_col() + 
  scale_x_discrete(labels = c("Zone", "Man")) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Man Coverage",
       y = "",
       title = "Defensive Holding Penalites More Likely During Man Coverage")

train_data %>% 
  select(contains("min_change_in_distance_times_speed"), contains("distance_from_opp"),  play_length,
         percentage_as_closest_defender, man_coverage, max_speed_differece, dh) %>% 
  plot_correlation()


```

# Modeling
###*Models
```{r}
# logistic reg model
lr_mod <- 
  logistic_reg() %>% 
  set_engine("glm")

# random forest model
rf_mod <- 
  rand_forest(trees = 1000, mtry = tune(), min_n = tune()) %>% 
  set_engine("ranger") %>% 
  set_mode("classification")
```

###*CV Folds
```{r}
# CV data
train_folds <- vfold_cv(train_data, v = 10, strata = dh)

```

###*Recipes
```{r}
# log_regression recipe
lr_rec <-
  recipe(
    dh ~ play_length + min_change_in_speed_10 + min_distance_from_opp + def_weight + off_height_adv + off_weight_adv + down +
      man_coverage + defenders_in_the_box + min_change_in_distance_times_speed_1 + max_speed_differece + nfl_id_off + nfl_id_def,
    data = train_data
  ) %>%
  step_YeoJohnson(all_numeric(), -nfl_id_off, -nfl_id_def) %>%
  step_center(all_numeric(), -nfl_id_off, -nfl_id_def) %>%
  step_scale(all_numeric(), -nfl_id_off, -nfl_id_def) %>%
  step_dummy(all_nominal(), -all_outcomes(), one_hot = TRUE) %>%
  update_role(nfl_id_off, nfl_id_def, new_role = "ID") %>% 
  themis::step_rose(dh)
  


# rand_forest recipe
rf_rec <-
  recipe(
    dh ~ play_length + min_change_in_speed + min_distance_from_opp + def_weight + off_height_adv + off_weight_adv + down,
    data = train_data
  ) %>%
  step_dummy(down) %>%
  themis::step_rose(dh)


```  

###*Workflow
```{r}
lr_wf <- 
  workflow() %>%
  add_recipe(lr_rec) %>% 
  add_model(lr_mod)

rf_wf <- workflow() %>% 
  add_recipe(rf_rec) %>% 
  add_model(rf_mod)
```

###*Logistic Regression Fit
```{r}
#parallel processing
doParallel::registerDoParallel()

# logistic regression fit
lr_fit <-
  lr_wf %>%
  fit_resamples(
    train_folds,
    metrics = metric_set(roc_auc, accuracy, sensitivity, specificity),
    control = control_resamples(save_pred = TRUE)
  )


lr_fit %>% 
  collect_metrics()

lr_fit %>% 
  conf_mat_resampled()

lr_fit %>% 
  collect_predictions() %>% 
  filter(.pred_1 > .90)

# final fit, fit on all training data, test on test data
final_lr_wf <- 
  lr_wf %>% 
  last_fit(data_split)

# accuracy drops a bit but still not too bad
final_lr_wf %>% 
  collect_metrics()

# final results on holdout set log_reg, still able to predict 93% of defensive holding plays correctly.
# we see about 21.6% false positives but that is ok. DH is a judgement call and we want to analyze those false positives
# for our analysis
final_lr_wf %>% 
  collect_predictions() %>% 
  bind_cols(select(test_data, min_distance_from_opp)) %>% 
  # filter(.pred_class == 1 & min_distance_from_opp > 1)
  # filter(.pred_1 >.75)
  conf_mat(dh, .pred_class)

final_lr_model <- 
  lr_wf %>% 
  fit(train_data)

final_lr_model %>% 
  pull_workflow_fit()

lr_modeling_list <- list(
  
  # feature data
  feature_data = feature_data,
  
  # lr recipe
  lr_rec = lr_rec,
  
  # lr workflow
  lr_wf = lr_wf,
  
  # lr final model
  final_lr_model = final_lr_model
  
)

write_rds(lr_modeling_list, "models/lr_modeling_list.rds")
```

###*Random Forest Fit
```{r}
rf_fit <-
  rf_wf %>%
  tune_grid(
    resamples = train_folds,
    grid      = 20,
    metrics   = metric_set(roc_auc, accuracy, sensitivity, specificity),
    control   = control_resamples(save_pred = TRUE))

rf_fit %>% 
  collect_metrics() %>% 
  filter(.metric == "sens") %>%
  arrange(desc(mean))
  select(mtry, min_n, mean) %>% 
  pivot_longer(mtry:min_n,
               names_to = "parameter",
               values_to = "value") %>% 
  ggplot(aes(value, mean)) +
  geom_point() +
  facet_wrap( ~ parameter, scales = "free_x")

rf_best <- rf_fit %>% 
  select_best("accuracy")

final_rf_mod <- 
  finalize_model(rf_mod, rf_best)

final_rf_wf <- 
  workflow() %>% 
  add_recipe(rf_rec) %>% 
  add_model(final_rf_mod)

final_rf_res <- 
  final_rf_wf %>% 
  last_fit(data_split)

# final results on holdout set rand forest
final_rf_res %>% 
  collect_predictions() %>% 
  conf_mat(dh, .pred_class)

# logistic regression model and rf model show almost identical results
    

```

# Grab Data for Analysis
```{r}

dh_plays <- closest_offensive_players_tbl %>% 
  unite(game_play, c(game_id, play_id)) %>% 
  pull(game_play)

evaluation_data <- separation_data %>%
  mutate(game_play = str_c(game_id, play_id, sep = "_")) %>%
  filter(!game_play %in% c(dh_plays)) %>%
  collect()
```

# Prepare Data for Model Prediction
```{r, warning=FALSE}

# use data prep function (which includes filter frame function)
prepped_data <- evaluation_data %>% 
  data_prep_function()



# use create features function
prediction_data_1 <- prepped_data %>%
  nest(-c(game_id, play_id, nfl_id_off)) %>% 
  mutate(features = map(data, purrr::possibly(create_features_function, otherwise = NA)))


# merge with players data
prediction_data_2 <- prediction_data_1 %>%
  select(-data) %>%
  unnest(features) %>%
  drop_na() %>%
  mutate(dh = dh %>% as.factor()) %>%
  # add offensive player weight and height
  left_join(
    select(
      player_data,
      nfl_id,
      off_height = height,
      off_weight = weight
    ),
    by = c("nfl_id_off" = "nfl_id")
  ) %>%
  # add defensive player weight and height
  left_join(
    select(
      player_data,
      nfl_id,
      def_height = height,
      def_weight = weight
    ),
    by = c("nfl_id_def" = "nfl_id")
  ) %>%
  # calculate weight and height adv
  mutate(off_height_adv = off_height - def_height,
         off_weight_adv = off_weight - def_weight,
         down = down %>% as.factor(),
         man_coverage = man_coverage %>% as.factor())
```

# Model Prediction Data
```{r}

model_prediction_tbl <- predict(final_lr_model, prediction_data_2, type = "prob") %>%
  bind_cols(predict(final_lr_model, prediction_data_2)) %>%
  bind_cols(prediction_data_2)


write_rds(model_prediction_tbl, "predictions/model_prediction_tbl.rds")
```

# Analysis
```{r}

model_prediction_tbl %>%
  filter(.pred_1 >=.80) %>% 
  count(nfl_id_def) %>% 
  arrange(desc(n)) %>% 
  left_join(select(model_prediction_tbl, nfl_id_def) %>% 
                     count(nfl_id_def), by = "nfl_id_def") %>% 
  rename(plays_predicted_dh = n.x, total_plays_defended = n.y) %>% 
  mutate(percentage = plays_predicted_dh/total_plays_defended) %>% 
  filter(total_plays_defended > 250) %>% 
  arrange(desc(percentage)) %>% 
  left_join(select(players_df, display_name, nfl_id), by = c("nfl_id_def" = "nfl_id"))
```

